-- =============================================================
-- BARANGAY PROFILING SAMPLE DATA (Merged Pregnancy + History)
-- =============================================================
-- Prerequisite:
-- 1) barangay_profiles table already exists
-- 2) Migrations 006 and 007 are applied
--
-- Run in Supabase SQL editor.

-- -----------------------------------------------------------------
-- Ensure merged columns exist (safe to run multiple times)
-- -----------------------------------------------------------------
ALTER TABLE public.barangay_profiles
  ADD COLUMN IF NOT EXISTS is_pregnant text CHECK (is_pregnant IN ('yes', 'no')),
  ADD COLUMN IF NOT EXISTS pregnancy_months integer CHECK (pregnancy_months >= 0 AND pregnancy_months <= 10),
  ADD COLUMN IF NOT EXISTS gravida integer CHECK (gravida >= 0),
  ADD COLUMN IF NOT EXISTS para integer CHECK (para >= 0),
  ADD COLUMN IF NOT EXISTS lmp date,
  ADD COLUMN IF NOT EXISTS edd date,
  ADD COLUMN IF NOT EXISTS prenatal_checkup_date date,
  ADD COLUMN IF NOT EXISTS pregnancy_risk_level text CHECK (pregnancy_risk_level IN ('low', 'moderate', 'high')),
  ADD COLUMN IF NOT EXISTS pregnancy_remarks text,
  ADD COLUMN IF NOT EXISTS has_hypertension text,
  ADD COLUMN IF NOT EXISTS has_diabetes text,
  ADD COLUMN IF NOT EXISTS has_asthma text,
  ADD COLUMN IF NOT EXISTS has_heart_disease text,
  ADD COLUMN IF NOT EXISTS past_surgeries text,
  ADD COLUMN IF NOT EXISTS current_medications text,
  ADD COLUMN IF NOT EXISTS allergies text,
  ADD COLUMN IF NOT EXISTS hospitalization_history text,
  ADD COLUMN IF NOT EXISTS family_hypertension text,
  ADD COLUMN IF NOT EXISTS family_diabetes text,
  ADD COLUMN IF NOT EXISTS family_asthma text,
  ADD COLUMN IF NOT EXISTS family_cancer text,
  ADD COLUMN IF NOT EXISTS smoking_status text,
  ADD COLUMN IF NOT EXISTS alcohol_intake text,
  ADD COLUMN IF NOT EXISTS exercise_frequency text,
  ADD COLUMN IF NOT EXISTS dietary_pattern text,
  ADD COLUMN IF NOT EXISTS personal_history_notes text,
  ADD COLUMN IF NOT EXISTS past_medical_history text,
  ADD COLUMN IF NOT EXISTS pmh_specify_allergy text,
  ADD COLUMN IF NOT EXISTS pmh_specify_organ_cancer text,
  ADD COLUMN IF NOT EXISTS pmh_specify_hepatitis_type text,
  ADD COLUMN IF NOT EXISTS pmh_highest_blood_pressure text,
  ADD COLUMN IF NOT EXISTS pmh_specify_pulmonary_tb_category text,
  ADD COLUMN IF NOT EXISTS pmh_specify_extrapulmonary_tb_category text,
  ADD COLUMN IF NOT EXISTS pmh_others_specify text,
  ADD COLUMN IF NOT EXISTS past_surgical_history text,
  ADD COLUMN IF NOT EXISTS family_history text,
  ADD COLUMN IF NOT EXISTS fh_specify_allergy text,
  ADD COLUMN IF NOT EXISTS fh_specify_organ_cancer text,
  ADD COLUMN IF NOT EXISTS fh_specify_hepatitis_type text,
  ADD COLUMN IF NOT EXISTS fh_highest_blood_pressure text,
  ADD COLUMN IF NOT EXISTS fh_specify_pulmonary_tb_category text,
  ADD COLUMN IF NOT EXISTS fh_specify_extrapulmonary_tb_category text,
  ADD COLUMN IF NOT EXISTS fh_others_specify text,
  ADD COLUMN IF NOT EXISTS smoking_packs_per_year text,
  ADD COLUMN IF NOT EXISTS alcohol_bottles_per_day text,
  ADD COLUMN IF NOT EXISTS illicit_drugs text,
  ADD COLUMN IF NOT EXISTS sexually_active text;

INSERT INTO public.barangay_profiles (
  membership_type,
  philhealth_no,
  last_name,
  first_name,
  middle_name,
  suffix,
  age,
  birthdate,
  civil_status,
  maiden_last_name,
  maiden_middle_name,
  educational_attainment,
  employment_status,
  employed_in,
  occupation,
  company_address,
  religion,
  blood_type,
  mother_last_name,
  mother_first_name,
  mother_middle_name,
  mother_birthdate,
  father_last_name,
  father_first_name,
  father_middle_name,
  father_birthdate,
  spouse_last_name,
  spouse_first_name,
  spouse_birthdate,
  current_barangay,
  current_street,
  current_city,
  current_province,
  permanent_barangay,
  permanent_street,
  permanent_city,
  permanent_province,
  email,
  mobile,
  is_pregnant,
  pregnancy_months,
  gravida,
  para,
  lmp,
  edd,
  prenatal_checkup_date,
  pregnancy_risk_level,
  pregnancy_remarks,
  has_hypertension,
  has_diabetes,
  has_asthma,
  has_heart_disease,
  past_surgeries,
  current_medications,
  allergies,
  hospitalization_history,
  family_hypertension,
  family_diabetes,
  family_asthma,
  family_cancer,
  smoking_status,
  alcohol_intake,
  exercise_frequency,
  dietary_pattern,
  personal_history_notes,
  past_medical_history,
  pmh_specify_allergy,
  pmh_specify_organ_cancer,
  pmh_specify_hepatitis_type,
  pmh_highest_blood_pressure,
  pmh_specify_pulmonary_tb_category,
  pmh_specify_extrapulmonary_tb_category,
  pmh_others_specify,
  past_surgical_history,
  family_history,
  fh_specify_allergy,
  fh_specify_organ_cancer,
  fh_specify_hepatitis_type,
  fh_highest_blood_pressure,
  fh_specify_pulmonary_tb_category,
  fh_specify_extrapulmonary_tb_category,
  fh_others_specify,
  smoking_packs_per_year,
  alcohol_bottles_per_day,
  illicit_drugs,
  sexually_active,
  created_at,
  updated_at
)
VALUES
(
  'member',
  '12-345678901-2',
  'Ramos',
  'Ana',
  'Dela Cruz',
  NULL,
  28,
  '1997-06-14',
  'married',
  'Santos',
  'Reyes',
  'college',
  'employed',
  'private',
  'Teacher',
  'Naga City Central School',
  'Roman Catholic',
  'O+',
  'Santos',
  'Lorna',
  'Dizon',
  '1971-05-10',
  'Ramos',
  'Mario',
  'Garcia',
  '1968-02-19',
  'Ramos',
  'Kevin',
  '1994-01-23',
  'Concepcion Pequeña',
  'Purok 2, San Jose St.',
  'Naga City',
  'Camarines Sur',
  'Concepcion Pequeña',
  'Purok 2, San Jose St.',
  'Naga City',
  'Camarines Sur',
  'ana.ramos@example.com',
  '09171234567',
  'yes',
  6,
  2,
  1,
  '2025-10-01',
  '2026-07-08',
  '2026-02-10',
  'moderate',
  'Routine prenatal care; advised monthly BP monitoring.',
  'no',
  'no',
  'no',
  'no',
  'Appendectomy (2016)',
  'Ferrous sulfate, folic acid',
  'Shrimp',
  'None',
  'mother',
  'none',
  'none',
  'none',
  'no',
  'no',
  '3x/week walk',
  'balanced',
  'Compliant with prenatal checkups.',
  'allergy|none',
  'Shrimp',
  NULL,
  NULL,
  '120/80',
  NULL,
  NULL,
  NULL,
  'Appendectomy (2016)',
  'hypertension|diabetes_mellitus',
  NULL,
  NULL,
  NULL,
  '150/90',
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  'no',
  'yes',
  NOW(),
  NOW()
),
(
  'member',
  '22-456789012-3',
  'Mendoza',
  'Lea',
  'Torres',
  NULL,
  34,
  '1991-11-02',
  'married',
  'Torres',
  'Castro',
  'college',
  'self_employed',
  NULL,
  'Online Seller',
  'Concepcion Grande, Naga City',
  'Roman Catholic',
  'A+',
  'Torres',
  'Emily',
  'Lopez',
  '1965-03-07',
  'Torres',
  'Rene',
  'Cruz',
  '1963-09-11',
  'Mendoza',
  'Paolo',
  '1989-04-26',
  'Concepcion Grande',
  'Purok 5, Maharlika Rd.',
  'Naga City',
  'Camarines Sur',
  'Concepcion Grande',
  'Purok 5, Maharlika Rd.',
  'Naga City',
  'Camarines Sur',
  'lea.mendoza@example.com',
  '09981234567',
  'yes',
  8,
  4,
  2,
  '2025-08-20',
  '2026-05-27',
  '2026-02-12',
  'high',
  'Previous preeclampsia history; referred to CHO physician.',
  'yes',
  'no',
  'no',
  'no',
  'CS (2018)',
  'Methyldopa, prenatal vitamins',
  'Penicillin',
  'Admitted for elevated BP (2026-01)',
  'father',
  'none',
  'none',
  'none',
  'no',
  'no',
  'light walk',
  'low-salt',
  'Needs close weekly BP follow-up.',
  'hypertension|allergy',
  'Penicillin',
  NULL,
  NULL,
  '160/100',
  NULL,
  NULL,
  NULL,
  'CS (2018)',
  'hypertension|coronary_artery_disease',
  NULL,
  NULL,
  NULL,
  '170/100',
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  'no',
  'yes',
  NOW(),
  NOW()
),
(
  'member',
  '33-567890123-4',
  'Villanueva',
  'Carlos',
  'Reyes',
  NULL,
  42,
  '1983-04-12',
  'married',
  NULL,
  NULL,
  'college',
  'employed',
  'government',
  'Barangay Clerk',
  'Barangay Hall, Peñafrancia',
  'Roman Catholic',
  'B+',
  'Reyes',
  'Amor',
  'Diaz',
  '1958-11-09',
  'Villanueva',
  'Felix',
  'Romero',
  '1956-01-31',
  'Villanueva',
  'Maricel',
  '1985-03-18',
  'Peñafrancia',
  'Zone 3, Riverside',
  'Naga City',
  'Camarines Sur',
  'Peñafrancia',
  'Zone 3, Riverside',
  'Naga City',
  'Camarines Sur',
  'carlos.villanueva@example.com',
  '09190001111',
  'no',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'yes',
  'yes',
  'no',
  'no',
  'None',
  'Metformin, amlodipine',
  'None',
  'None',
  'yes',
  'yes',
  'none',
  'none',
  'former',
  'occasional',
  '2x/week cycling',
  'reduced sugar',
  'Monitored under NCD program.',
  'diabetes_mellitus|hypertension',
  NULL,
  NULL,
  NULL,
  '150/95',
  NULL,
  NULL,
  NULL,
  'None',
  'diabetes_mellitus|hypertension',
  NULL,
  NULL,
  NULL,
  '160/100',
  NULL,
  NULL,
  NULL,
  '8',
  '2',
  'no',
  'yes',
  NOW(),
  NOW()
),
(
  'dependent',
  NULL,
  'Garcia',
  'Mikaela',
  'Lopez',
  NULL,
  19,
  '2006-02-01',
  'single',
  NULL,
  NULL,
  'senior_high',
  'student',
  NULL,
  'Student',
  NULL,
  'Born Again',
  'AB+',
  'Garcia',
  'Jennifer',
  'Santos',
  '1982-08-15',
  'Garcia',
  'Noel',
  'Lopez',
  '1980-12-21',
  NULL,
  NULL,
  NULL,
  'Calauag',
  'Purok 1, Calauag',
  'Naga City',
  'Camarines Sur',
  'Calauag',
  'Purok 1, Calauag',
  'Naga City',
  'Camarines Sur',
  'mikaela.garcia@example.com',
  '09175556666',
  'no',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'no',
  'no',
  'yes',
  'no',
  'None',
  'Salbutamol inhaler PRN',
  'Dust',
  'None',
  'none',
  'none',
  'yes',
  'none',
  'no',
  'no',
  'daily walking',
  'balanced',
  'Known intermittent asthma.',
  'asthma|allergy',
  'Dust',
  NULL,
  NULL,
  '110/70',
  NULL,
  NULL,
  NULL,
  'None',
  'asthma',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  'no',
  'no',
  NOW(),
  NOW()
),
(
  'member',
  '44-678901234-5',
  'De Guzman',
  'Rosario',
  'M.',
  NULL,
  63,
  '1963-10-05',
  'widowed',
  NULL,
  NULL,
  'high_school',
  'retired',
  NULL,
  'Retired Vendor',
  NULL,
  'Roman Catholic',
  'O-',
  'Martinez',
  'Dolores',
  'P.',
  '1938-07-12',
  'De Guzman',
  'Alberto',
  'R.',
  '1936-04-03',
  NULL,
  NULL,
  NULL,
  'Pacol',
  'Sitio Centro, Pacol',
  'Naga City',
  'Camarines Sur',
  'Pacol',
  'Sitio Centro, Pacol',
  'Naga City',
  'Camarines Sur',
  'rosario.deguzman@example.com',
  '09223334444',
  'no',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'yes',
  'yes',
  'no',
  'yes',
  'Cholecystectomy (2009)',
  'Losartan, atorvastatin',
  'None',
  'Admitted due to chest pain (2023)',
  'yes',
  'yes',
  'none',
  'none',
  'former',
  'none',
  'light stretching',
  'low-fat',
  'Needs periodic cardiovascular follow-up.',
  'hypertension|hyperlipidemia|coronary_artery_disease',
  NULL,
  NULL,
  NULL,
  '170/100',
  NULL,
  NULL,
  NULL,
  'Cholecystectomy (2009)',
  'hypertension|coronary_artery_disease|diabetes_mellitus',
  NULL,
  NULL,
  NULL,
  '180/100',
  NULL,
  NULL,
  NULL,
  '20',
  '0',
  'no',
  'no',
  NOW(),
  NOW()
);

-- Optional: verify inserted rows
-- SELECT id, last_name, first_name, current_barangay, is_pregnant, pregnancy_risk_level
-- FROM public.barangay_profiles
-- ORDER BY created_at DESC
-- LIMIT 20;
