// Plain utility — no "use server" — safe to import anywhere

import type { BarangayProfileFormData } from "@/components/barangay-profiling/barangay-profile-form";
import type { BarangayProfile } from "@/components/barangay-profiling/barangay-profiles-list";

// ─── DB row → UI model ────────────────────────────────────────────────────────

export function rowToProfile(row: Record<string, unknown>): BarangayProfile {
  const str = (v: unknown) => (v == null ? "" : String(v));
  return {
    id: str(row.id),
    createdAt: str(row.created_at),
    membershipType: (row.membership_type as "member" | "dependent") || "",
    philhealthNo: str(row.philhealth_no),
    lastName: str(row.last_name),
    firstName: str(row.first_name),
    middleName: str(row.middle_name),
    suffix: str(row.suffix),
    age: str(row.age),
    birthdate: str(row.birthdate),
    civilStatus: str(row.civil_status),
    maidenLastName: str(row.maiden_last_name),
    maidenMiddleName: str(row.maiden_middle_name),
    educationalAttainment: str(row.educational_attainment),
    employmentStatus: str(row.employment_status),
    employedIn: str(row.employed_in),
    occupation: str(row.occupation),
    companyAddress: str(row.company_address),
    religion: str(row.religion),
    bloodType: str(row.blood_type),
    motherLastName: str(row.mother_last_name),
    motherFirstName: str(row.mother_first_name),
    motherMiddleName: str(row.mother_middle_name),
    motherBirthdate: str(row.mother_birthdate),
    fatherLastName: str(row.father_last_name),
    fatherFirstName: str(row.father_first_name),
    fatherMiddleName: str(row.father_middle_name),
    fatherBirthdate: str(row.father_birthdate),
    spouseLastName: str(row.spouse_last_name),
    spouseFirstName: str(row.spouse_first_name),
    spouseBirthdate: str(row.spouse_birthdate),
    currentBarangay: str(row.current_barangay),
    currentStreet: str(row.current_street),
    currentCity: str(row.current_city),
    currentProvince: str(row.current_province),
    permanentBarangay: str(row.permanent_barangay),
    permanentStreet: str(row.permanent_street),
    permanentCity: str(row.permanent_city),
    permanentProvince: str(row.permanent_province),
    email: str(row.email),
    mobile: str(row.mobile),
    isPregnant: (row.is_pregnant as "yes" | "no") || "",
    pregnancyMonths: str(row.pregnancy_months),
    gravida: str(row.gravida),
    para: str(row.para),
    lmp: str(row.lmp),
    edd: str(row.edd),
    prenatalCheckupDate: str(row.prenatal_checkup_date),
    pregnancyRiskLevel: str(row.pregnancy_risk_level),
    pregnancyRemarks: str(row.pregnancy_remarks),
    hasHypertension: str(row.has_hypertension),
    hasDiabetes: str(row.has_diabetes),
    hasAsthma: str(row.has_asthma),
    hasHeartDisease: str(row.has_heart_disease),
    pastSurgeries: str(row.past_surgeries),
    currentMedications: str(row.current_medications),
    allergies: str(row.allergies),
    hospitalizationHistory: str(row.hospitalization_history),
    pastMedicalHistory: str(row.past_medical_history),
    pmhSpecifyAllergy: str(row.pmh_specify_allergy),
    pmhSpecifyOrganCancer: str(row.pmh_specify_organ_cancer),
    pmhSpecifyHepatitisType: str(row.pmh_specify_hepatitis_type),
    pmhHighestBloodPressure: str(row.pmh_highest_blood_pressure),
    pmhSpecifyPulmonaryTbCategory: str(row.pmh_specify_pulmonary_tb_category),
    pmhSpecifyExtrapulmonaryTbCategory: str(
      row.pmh_specify_extrapulmonary_tb_category,
    ),
    pmhOthersSpecify: str(row.pmh_others_specify),
    pastSurgicalHistory: str(row.past_surgical_history),
    familyHypertension: str(row.family_hypertension),
    familyDiabetes: str(row.family_diabetes),
    familyAsthma: str(row.family_asthma),
    familyCancer: str(row.family_cancer),
    familyHistory: str(row.family_history),
    fhSpecifyAllergy: str(row.fh_specify_allergy),
    fhSpecifyOrganCancer: str(row.fh_specify_organ_cancer),
    fhSpecifyHepatitisType: str(row.fh_specify_hepatitis_type),
    fhHighestBloodPressure: str(row.fh_highest_blood_pressure),
    fhSpecifyPulmonaryTbCategory: str(row.fh_specify_pulmonary_tb_category),
    fhSpecifyExtrapulmonaryTbCategory: str(
      row.fh_specify_extrapulmonary_tb_category,
    ),
    fhOthersSpecify: str(row.fh_others_specify),
    smokingStatus: str(row.smoking_status),
    smokingPacksPerYear: str(row.smoking_packs_per_year),
    alcoholIntake: str(row.alcohol_intake),
    alcoholBottlesPerDay: str(row.alcohol_bottles_per_day),
    illicitDrugs: str(row.illicit_drugs),
    sexuallyActive: str(row.sexually_active),
    exerciseFrequency: str(row.exercise_frequency),
    dietaryPattern: str(row.dietary_pattern),
    personalHistoryNotes: str(row.personal_history_notes),
  };
}

// ─── UI model → DB row ────────────────────────────────────────────────────────

export function formDataToRow(
  data: BarangayProfileFormData,
  userId?: string,
): Record<string, unknown> {
  const nullable = (v: string) => (v.trim() === "" ? null : v.trim());
  const nullableNum = (v: string) => {
    const n = parseInt(v, 10);
    return isNaN(n) ? null : n;
  };

  return {
    membership_type: data.membershipType || null,
    philhealth_no: nullable(data.philhealthNo),
    last_name: data.lastName.trim(),
    first_name: data.firstName.trim(),
    middle_name: nullable(data.middleName),
    suffix: nullable(data.suffix) === "none" ? null : nullable(data.suffix),
    age: nullableNum(data.age),
    birthdate: nullable(data.birthdate),
    civil_status: nullable(data.civilStatus),
    maiden_last_name: nullable(data.maidenLastName),
    maiden_middle_name: nullable(data.maidenMiddleName),
    educational_attainment: nullable(data.educationalAttainment),
    employment_status: nullable(data.employmentStatus),
    employed_in: nullable(data.employedIn),
    occupation: nullable(data.occupation),
    company_address: nullable(data.companyAddress),
    religion: nullable(data.religion),
    blood_type: nullable(data.bloodType),
    mother_last_name: nullable(data.motherLastName),
    mother_first_name: nullable(data.motherFirstName),
    mother_middle_name: nullable(data.motherMiddleName),
    mother_birthdate: nullable(data.motherBirthdate),
    father_last_name: nullable(data.fatherLastName),
    father_first_name: nullable(data.fatherFirstName),
    father_middle_name: nullable(data.fatherMiddleName),
    father_birthdate: nullable(data.fatherBirthdate),
    spouse_last_name: nullable(data.spouseLastName),
    spouse_first_name: nullable(data.spouseFirstName),
    spouse_birthdate: nullable(data.spouseBirthdate),
    current_barangay: nullable(data.currentBarangay),
    current_street: nullable(data.currentStreet),
    current_city: nullable(data.currentCity),
    current_province: nullable(data.currentProvince),
    permanent_barangay: nullable(data.permanentBarangay),
    permanent_street: nullable(data.permanentStreet),
    permanent_city: nullable(data.permanentCity),
    permanent_province: nullable(data.permanentProvince),
    email: nullable(data.email),
    mobile: nullable(data.mobile),
    is_pregnant: data.isPregnant || null,
    pregnancy_months: nullableNum(data.pregnancyMonths),
    gravida: nullableNum(data.gravida),
    para: nullableNum(data.para),
    lmp: nullable(data.lmp),
    edd: nullable(data.edd),
    prenatal_checkup_date: nullable(data.prenatalCheckupDate),
    pregnancy_risk_level: nullable(data.pregnancyRiskLevel),
    pregnancy_remarks: nullable(data.pregnancyRemarks),
    has_hypertension: nullable(data.hasHypertension),
    has_diabetes: nullable(data.hasDiabetes),
    has_asthma: nullable(data.hasAsthma),
    has_heart_disease: nullable(data.hasHeartDisease),
    past_surgeries: nullable(data.pastSurgeries),
    current_medications: nullable(data.currentMedications),
    allergies: nullable(data.allergies),
    hospitalization_history: nullable(data.hospitalizationHistory),
    past_medical_history: nullable(data.pastMedicalHistory),
    pmh_specify_allergy: nullable(data.pmhSpecifyAllergy),
    pmh_specify_organ_cancer: nullable(data.pmhSpecifyOrganCancer),
    pmh_specify_hepatitis_type: nullable(data.pmhSpecifyHepatitisType),
    pmh_highest_blood_pressure: nullable(data.pmhHighestBloodPressure),
    pmh_specify_pulmonary_tb_category: nullable(
      data.pmhSpecifyPulmonaryTbCategory,
    ),
    pmh_specify_extrapulmonary_tb_category: nullable(
      data.pmhSpecifyExtrapulmonaryTbCategory,
    ),
    pmh_others_specify: nullable(data.pmhOthersSpecify),
    past_surgical_history: nullable(data.pastSurgicalHistory),
    family_hypertension: nullable(data.familyHypertension),
    family_diabetes: nullable(data.familyDiabetes),
    family_asthma: nullable(data.familyAsthma),
    family_cancer: nullable(data.familyCancer),
    family_history: nullable(data.familyHistory),
    fh_specify_allergy: nullable(data.fhSpecifyAllergy),
    fh_specify_organ_cancer: nullable(data.fhSpecifyOrganCancer),
    fh_specify_hepatitis_type: nullable(data.fhSpecifyHepatitisType),
    fh_highest_blood_pressure: nullable(data.fhHighestBloodPressure),
    fh_specify_pulmonary_tb_category: nullable(data.fhSpecifyPulmonaryTbCategory),
    fh_specify_extrapulmonary_tb_category: nullable(
      data.fhSpecifyExtrapulmonaryTbCategory,
    ),
    fh_others_specify: nullable(data.fhOthersSpecify),
    smoking_status: nullable(data.smokingStatus),
    smoking_packs_per_year: nullable(data.smokingPacksPerYear),
    alcohol_intake: nullable(data.alcoholIntake),
    alcohol_bottles_per_day: nullable(data.alcoholBottlesPerDay),
    illicit_drugs: nullable(data.illicitDrugs),
    sexually_active: nullable(data.sexuallyActive),
    exercise_frequency: nullable(data.exerciseFrequency),
    dietary_pattern: nullable(data.dietaryPattern),
    personal_history_notes: nullable(data.personalHistoryNotes),
    ...(userId ? { created_by: userId } : {}),
    updated_at: new Date().toISOString(),
  };
}
